/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.DbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelompok A
 * Adelia Rahmawati 18311243
 * Agung Pambudi 18311052
 */
public class frmBarang extends javax.swing.JFrame {

    DbConnection dbsetting;
    String driver, database, user, pass;
    int row = 0;
    String data[] = new String[5];
    Object table;
    static int c;

    /**
     * Creates new form frmBarang
     */
    public frmBarang() {

        String htitle[] = {"KodeBarang", "NamaBarang", "Harga", "Satuan", "Stok"};

        initComponents();
        setLocationRelativeTo(this);

        dbsetting = new DbConnection();
        driver = dbsetting.settingPanel("DBDriver");
        database = dbsetting.settingPanel("DBDatabase");
        user = dbsetting.settingPanel("DBUsername");
        pass = dbsetting.settingPanel("DBPassword");
        tblModel = new DefaultTableModel(null, htitle);

        tblDataBarang.setModel(tblModel);

        autoNumber();
        setTampil();
        setBersih();
        setAwal();
    }

    private void setBersih() {
        // txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtHargaBarang.setText("");
        cboSatuan.setSelectedIndex(0);
        txtStok.setText("");
        txtPencarian.setText("");
    }

    private void setAwal() {
        cmdBaru.setEnabled(true);
        cmdSimpan.setEnabled(true);
        cmdUbah.setEnabled(false);
        cmdHapus.setEnabled(false);
        cmdKeluar.setEnabled(true);
    }

    private void setAkhir() {
        cmdBaru.setEnabled(true);
        cmdSimpan.setEnabled(false);
        cmdUbah.setEnabled(true);
        cmdHapus.setEnabled(true);
        cmdKeluar.setEnabled(true);
    }

    private void setRefreshData() {
        int count = tblModel.getRowCount();
        int x = 1;
        while (x <= count) {
            tblModel.removeRow(0);
            x = x + 1;
        }
    }

    private void setTampil() {
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String sql = "SELECT * FROM barang ORDER BY kodebarang";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                tblModel.addRow(data);
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void autoNumber() {
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String sql = "SELECT MAX(RIGHT(kodebarang, 5)) AS no FROM barang";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                if (rs.first() == false) {
                    txtKodeBarang.setText("B-00001");
                } else {
                    rs.last();
                    int kodebarang1 = rs.getInt(1) + 1;
                    String no = String.valueOf(kodebarang1);
                    int noLong = no.length();
                    for (int a = 0; a < 5 - noLong; a++) {
                        no = "0" + no;
                    }
                    txtKodeBarang.setText("B-" + no);
                }
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaBarang = new javax.swing.JTextField();
        cboSatuan = new javax.swing.JComboBox<>();
        txtStok = new javax.swing.JTextField();
        txtPencarian = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdBaru = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Harga Barang");

        jLabel4.setText("Satuan");

        jLabel5.setText("Stok");

        jLabel6.setText("Pencarian Data Barang");

        txtKodeBarang.setEditable(false);

        cboSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PCS", "UNIT", "PACK", "BOX" }));

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPencarianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPencarianKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(cboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(63, 63, 63)
                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(cboSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        cmdBaru.setText("Baru");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmdBaru)
                .addGap(18, 18, 18)
                .addComponent(cmdSimpan)
                .addGap(18, 18, 18)
                .addComponent(cmdUbah)
                .addGap(18, 18, 18)
                .addComponent(cmdHapus)
                .addGap(18, 18, 18)
                .addComponent(cmdKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        tblDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Satuan", "Stok"
            }
        ));
        tblDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataBarangMouseClicked(evt);
            }
        });
        tblDataBarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDataBarangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblDataBarang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Data Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataBarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblDataBarangPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataBarangPropertyChange

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        if (txtKodeBarang.getText().equals("") || txtNamaBarang.getText().equals("") || txtHargaBarang.getText().equals("") || txtStok.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Dulu Datanya !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "UPDATE barang SET namabarang=?, harga=?, satuan=?, stok=? WHERE kodebarang=?";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(5, txtKodeBarang.getText());
                stmt.setString(1, txtNamaBarang.getText());
                stmt.setString(2, txtHargaBarang.getText());
                stmt.setString(3, (String) cboSatuan.getSelectedItem());
                stmt.setString(4, txtStok.getText());
                stmt.executeUpdate();

                stmt.close();
                conn.close();

                setRefreshData();
                setBersih();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diedit !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                txtKodeBarang.requestFocus();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Edit !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
        setBersih();
        setAwal();
        txtKodeBarang.requestFocus();
    }//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed

        if (txtKodeBarang.getText().equals("") || txtNamaBarang.getText().equals("") || txtHargaBarang.getText().equals("") || txtStok.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Seluruh Data !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "INSERT INTO barang VALUES (?, ?, ?, ?, ?)";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(1, txtKodeBarang.getText());
                stmt.setString(2, txtNamaBarang.getText());
                stmt.setString(3, txtHargaBarang.getText());
                stmt.setString(4, (String) cboSatuan.getSelectedItem());
                stmt.setString(5, txtStok.getText());
                stmt.executeUpdate();

                data[0] = txtKodeBarang.getText();
                data[1] = txtNamaBarang.getText();
                data[2] = txtHargaBarang.getText();
                data[3] = cboSatuan.getSelectedItem().toString();
                data[4] = txtStok.getText();
                tblModel.insertRow(0, data);

                stmt.close();

                setRefreshData();
                setBersih();

                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                txtKodeBarang.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Kode Barang Sudah Ada !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void tblDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataBarangMouseClicked
        int row;

        if (evt.getClickCount() == 1) {
            row = tblDataBarang.getSelectedRow();
            txtKodeBarang.setText(tblDataBarang.getValueAt(row, 0).toString());
            txtNamaBarang.setText(tblDataBarang.getValueAt(row, 1).toString());
            txtHargaBarang.setText(tblDataBarang.getValueAt(row, 2).toString());
            cboSatuan.setSelectedItem(tblDataBarang.getValueAt(row, 3).toString());
            txtStok.setText(tblDataBarang.getValueAt(row, 4).toString());
        }

        setAkhir();
    }//GEN-LAST:event_tblDataBarangMouseClicked

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        if (txtKodeBarang.getText().equals("") || txtNamaBarang.getText().equals("") || txtHargaBarang.getText().equals("") || txtStok.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Dulu Datanya !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "DELETE FROM barang WHERE kodebarang=?";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(1, txtKodeBarang.getText());
                stmt.executeUpdate();

                data[0] = txtKodeBarang.getText();
                data[1] = txtNamaBarang.getText();
                data[2] = txtHargaBarang.getText();
                data[3] = cboSatuan.getSelectedItem().toString();
                data[4] = txtStok.getText();
                tblModel.removeRow(row);

                stmt.close();
                conn.close();

                setRefreshData();
                setBersih();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                txtKodeBarang.requestFocus();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            setAwal();
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void txtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyReleased
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String cari = txtPencarian.getText();
            String sql = "SELECT * FROM barang WHERE kodebarang LIKE '%" + cari + "%' OR namabarang LIKE '%" + cari + "%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                tblModel.addRow(data);
            }

            for (int i = 0; i < count; i++) {
                tblModel.removeRow(0);
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_txtPencarianKeyReleased

    private void txtPencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyPressed

    }//GEN-LAST:event_txtPencarianKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBarang().setVisible(true);
            }
        });
    }

    private final javax.swing.table.DefaultTableModel tblModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboSatuan;
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataBarang;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtPencarian;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
