/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.DbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelompok A
 * Adelia Rahmawati 18311243
 * Agung Pambudi 18311052
 */
public class frmSuplier extends javax.swing.JFrame {

    DbConnection dbsetting;
    String driver, database, user, pass;
    int row = 0;
    String data[] = new String[4];
    Object table;
    static int c;

    /**
     * Creates new form frmBarang
     */
    public frmSuplier() {

        String htitle[] = {"Kode Suplier", "Nama Suplier", "Alamat", "No. Telepon"};

        initComponents();
        setLocationRelativeTo(this);

        dbsetting = new DbConnection();
        driver = dbsetting.settingPanel("DBDriver");
        database = dbsetting.settingPanel("DBDatabase");
        user = dbsetting.settingPanel("DBUsername");
        pass = dbsetting.settingPanel("DBPassword");
        tblModel = new DefaultTableModel(null, htitle);

        tblDataBarang.setModel(tblModel);

        autoNumber();
        setTampil();
        setBersih();
        setAwal();
    }

    private void setBersih() {
        // txtKodeBarang.setText("");
        txtNamaSuplier.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
        txtPencarian.setText("");
    }

    private void setAwal() {
        cmdBaru.setEnabled(true);
        cmdSimpan.setEnabled(true);
        cmdUbah.setEnabled(false);
        cmdHapus.setEnabled(false);
        cmdKeluar.setEnabled(true);
    }

    private void setAkhir() {
        cmdBaru.setEnabled(true);
        cmdSimpan.setEnabled(false);
        cmdUbah.setEnabled(true);
        cmdHapus.setEnabled(true);
        cmdKeluar.setEnabled(true);
    }

    private void setRefreshData() {
        int count = tblModel.getRowCount();
        int x = 1;
        while (x <= count) {
            tblModel.removeRow(0);
            x = x + 1;
        }
    }

    private void setTampil() {
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String sql = "SELECT * FROM suplier ORDER BY kodesuplier";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                tblModel.addRow(data);
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void autoNumber() {
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String sql = "SELECT MAX(RIGHT(kodesuplier, 5)) AS no FROM suplier";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                if (rs.first() == false) {
                    txtKodeSuplier.setText("S-00001");
                } else {
                    rs.last();
                    int kodebarang1 = rs.getInt(1) + 1;
                    String no = String.valueOf(kodebarang1);
                    int noLong = no.length();
                    for (int a = 0; a < 5 - noLong; a++) {
                        no = "0" + no;
                    }
                    txtKodeSuplier.setText("S-" + no);
                }
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeSuplier = new javax.swing.JTextField();
        txtNamaSuplier = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        cmdBaru = new javax.swing.JButton();
        cmdSimpan = new javax.swing.JButton();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataBarang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode Suplier");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 18, -1, -1));

        jLabel2.setText("Nama Suplier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, -1, -1));

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 81, -1, -1));

        jLabel5.setText("No. Telepon");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 153, -1, -1));

        txtKodeSuplier.setEditable(false);
        jPanel1.add(txtKodeSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 15, 193, -1));
        jPanel1.add(txtNamaSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 46, 193, -1));
        jPanel1.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 150, 191, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 81, 190, 51));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdBaru.setText("Baru");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 28, 97, -1));

        cmdSimpan.setText("Simpan");
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 69, 97, -1));

        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });
        jPanel2.add(cmdUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 110, 97, -1));

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });
        jPanel2.add(cmdHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 151, 97, -1));

        cmdKeluar.setText("Keluar");
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 192, 97, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 60, 130, 240));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Suplier", "Nama Suplier", "Alamat", "No. Telepon"
            }
        ));
        tblDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataBarangMouseClicked(evt);
            }
        });
        tblDataBarang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblDataBarangPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblDataBarang);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 61, 430, 89));

        jLabel6.setText("Pencarian Data Suplier");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 26, -1, -1));

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPencarianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPencarianKeyReleased(evt);
            }
        });
        jPanel3.add(txtPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 23, 260, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 315, 466, 170));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Data Suplier");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDataBarangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblDataBarangPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataBarangPropertyChange

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        if (txtKodeSuplier.getText().equals("") || txtNamaSuplier.getText().equals("") || txtAlamat.getText().equals("") || txtTelepon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Dulu Datanya !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "UPDATE suplier SET namasuplier=?, alamat=?, notelepon=? WHERE kodesuplier=?";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(4, txtKodeSuplier.getText());
                stmt.setString(1, txtNamaSuplier.getText());
                stmt.setString(2, txtAlamat.getText());             
                stmt.setString(3, txtTelepon.getText());
                stmt.executeUpdate();

                stmt.close();
                conn.close();

                setRefreshData();
                setBersih();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diedit !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                autoNumber();
                txtNamaSuplier.requestFocus();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Edit !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda ingin keluar ?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
        setBersih();
        setAwal();
        autoNumber();
        txtNamaSuplier.requestFocus();
    }//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed

        if (txtKodeSuplier.getText().equals("") || txtNamaSuplier.getText().equals("") || txtAlamat.getText().equals("") || txtTelepon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Seluruh Data !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "INSERT INTO suplier VALUES (?, ?, ?, ?)";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(1, txtKodeSuplier.getText());
                stmt.setString(2, txtNamaSuplier.getText());
                stmt.setString(3, txtAlamat.getText());                
                stmt.setString(4, txtTelepon.getText());
                stmt.executeUpdate();

                data[0] = txtKodeSuplier.getText();
                data[1] = txtNamaSuplier.getText();
                data[2] = txtAlamat.getText();                
                data[3] = txtTelepon.getText();
                tblModel.insertRow(0, data);

                stmt.close();

                setRefreshData();
                setBersih();

                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                autoNumber();
                txtNamaSuplier.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Kode Barang Sudah Ada !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cmdSimpanActionPerformed

    private void tblDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataBarangMouseClicked
        int row;

        if (evt.getClickCount() == 1) {
            row = tblDataBarang.getSelectedRow();
            txtKodeSuplier.setText(tblDataBarang.getValueAt(row, 0).toString());
            txtNamaSuplier.setText(tblDataBarang.getValueAt(row, 1).toString());
            txtAlamat.setText(tblDataBarang.getValueAt(row, 2).toString());            
            txtTelepon.setText(tblDataBarang.getValueAt(row, 3).toString());
        }

        setAkhir();
    }//GEN-LAST:event_tblDataBarangMouseClicked

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
        if (txtKodeSuplier.getText().equals("") || txtNamaSuplier.getText().equals("") || txtAlamat.getText().equals("") || txtTelepon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Dulu Datanya !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Class.forName(driver);
                Connection conn = DriverManager.getConnection(database, user, pass);
                String sql = "DELETE FROM suplier WHERE kodesuplier=?";
                PreparedStatement stmt = conn.prepareStatement(sql);

                stmt.setString(1, txtKodeSuplier.getText());
                stmt.executeUpdate();

                data[0] = txtKodeSuplier.getText();
                data[1] = txtNamaSuplier.getText();
                data[2] = txtAlamat.getText();                
                data[3] = txtTelepon.getText();
                tblModel.removeRow(row);

                stmt.close();
                conn.close();

                setRefreshData();
                setBersih();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus !!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                setTampil();
                autoNumber();
                txtNamaSuplier.requestFocus();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus !!!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            setAwal();
        }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void txtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyReleased
        int count = tblModel.getRowCount();

        try {
            Class.forName(driver);
            Connection conn = DriverManager.getConnection(database, user, pass);
            String cari = txtPencarian.getText();
            String sql = "SELECT * FROM suplier WHERE kodesuplier LIKE '%" + cari + "%' OR namasuplier LIKE '%" + cari + "%'";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);                
                tblModel.addRow(data);
            }

            for (int i = 0; i < count; i++) {
                tblModel.removeRow(0);
            }

            rs.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_txtPencarianKeyReleased

    private void txtPencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyPressed

    }//GEN-LAST:event_txtPencarianKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSuplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSuplier().setVisible(true);
            }
        });
    }

    private final javax.swing.table.DefaultTableModel tblModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDataBarang;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtKodeSuplier;
    private javax.swing.JTextField txtNamaSuplier;
    private javax.swing.JTextField txtPencarian;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
